### ISSUE TITLE
Instructions for building and testing?

### ISSUE THREAD

**Issue by sharno** [andyarvanitis/purescript-native-go-ffi#8]
Are there some helpful instructions to build and test the ffi here?
Also, how do you think this repo could be kept in sync with any changes in the original packages?

edit: I managed to build a toy project that uses go-ffi but it go modules just pulls everything from github. Trying to make it use the local version that I'm working on doesn't seem to work

I've tried using the `replace` directive in the ffi-loader .mod file but it just throws this error:
```
module project.localhost/purescript-native/ffi-loader


require (
  github.com/purescript-native/go-ffi v0.0.0
)

replace github.com/purescript-native/go-ffi => /Users/sharno/projects/purescript-native-go-ffi
```

```
go: project.localhost/purescript-native/ffi-loader@v0.0.0-00010101000000-000000000000 requires
	github.com/purescript-native/go-ffi@v0.0.0: reading github.com/purescript-native/go-ffi/go.mod at revision v0.0.0: unknown revision v0.0.0
psgo: callProcess: go "build" "project.localhost/purescript-native/output/Main" (exit 1): failed

```

**Comment by sharno** [comment]
I managed to create my test project in a parent folder to this repo to make it work, not sure if there's a better way but Go's modules are still not intuitive to work with

**Comment by andyarvanitis** [comment]
For your question regarding a `replace` directive in `go.mod`, you need to add it to the top-level (working directory) `go.mod`, not the ffi-loader one. For example:

```
module project.localhost/example
  
replace project.localhost/purescript-native/ffi-loader => /Users/me/Projects/PureScript/Test/purescript-native

replace project.localhost/purescript-native/output => /Users/me/Projects/PureScript/Test/output

replace github.com/purescript-native/go-ffi => /Users/me/Projects/PureScript/purescript-go-ffi
```

Go modules do take a bit of getting used to.
Hope that helps.

**Comment by andyarvanitis** [comment]
Also, for your package version/syncing question: it's still under discussion. We've talked about it a little bit here: https://github.com/spacchetti/spago/issues/355#issuecomment-521500083

**Comment by sharno** [comment]
Awesome, I'll try what you suggested later and reopen the issue if it didn't work

I guess tagging the FFI with the psc-packages version is ok for the beginning, but I guess thinking of a better way to handle that might be worth it later on. I'll try to help as much as I can
